### PR TITLE
compliance-masonry: Update to 1.1.3 to support macos High Sierra

### PR DESCRIPTION
**Pull request by chris-griffin**
Closes #https://github.com/narmitech/docs/issues/199

@phillbaker also mind taking at the initial commit to master(https://github.com/narmitech/homebrew-versions/commit/e6d65a3ccc63c89ead68c29f47457e1df302f261)

### CODE REVIEW

**Comment by phillbaker** [comment]
e6d65a3 was just the import from the gist?

**Comment by phillbaker** [comment]
This lgtm - just the question about naming of this repo on the original commit. FWIW I think I named it versions originally because the postgres 9.3 version was missing from homebrew. 🤷‍♂️

**Comment by phillbaker** [comment]
Want to update https://github.com/narmitech/docs/blob/master/dev-on-boarding/setup.md as well?

**Comment by chris-griffin** [comment]
Yeah, will update the docs. In order to be able to do `brew tap narmi/homebrew` this repo would have to be named 'homebrew-homebrew' which seems strange. 'homebrew-versions' is also a bit weird, but I figured I'd just mirror it 🤷‍♂️

**Pull request merged**
